services:

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      #1001 is the user "everyone"
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - .\deluge\config:/config
      - torrent_folder:/watch
      - books_source:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped  


  move-books:
    image: gregkwoods/move-books
    container_name: move-books
    build:
      context: .
      dockerfile: .\move-books\Dockerfile
    ports:
      - "5051:5000"
    volumes:
      - books_destination:/app/kavita_destination
      - books_source:/app/books_source

volumes:
  # These volumes are for local use.
  #   If the kavita uploader was run on the proxmox server, 
  #   we could use simple bind mounts
  torrent_folder:
    driver: local
    driver_opts:
      type: cifs
      device: "//10.0.1.2/everyone/torrent"
      o: "username=everyone,password=********,uid=1001,gid=1001,vers=3.0"
  books_source:
    driver: local
    driver_opts:
      typeS: cifs
      device: "//10.0.1.2/everyone/downloads-temp"
      o: "username=everyone,password=********,uid=1001,gid=1001,vers=3.0"
  books_destination:
    driver: local
    driver_opts:
      type: cifs
      device: "//10.0.1.2/everyone/books-ready-for-kavita"
      o: "username=everyone,password=********,uid=1001,gid=1001,vers=3.0"