services:

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      #1001 is the user "everyone"
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ./deluge/config:/config
      - /home/gadmin/shares/everyone/torrent:/watch
      - /home/gadmin/shares/everyone/downloads-temp:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped  


  move-books:
    image: gregkwoods/move-books
    build:
      context: ./move-books
    container_name: move-books
    volumes:
      - /home/gadmin/shares/everyone/downloads-temp:/books_source
      - /home/gadmin/shares/everyone/books-ready-for-kavita:/books_destination
    user: "1001:1001" #everyone:everyone
    restart: unless-stopped
